FROM golang:1.17.9-alpine

# Build and run indexer
RUN mkdir /work
WORKDIR /work
ADD . ./
WORKDIR /work/cmd/algorand-indexer
RUN go build

# The sleep is to wait until postgres starts
CMD ["/bin/sh", "-c", "\
  echo $ALGOD_NET && \
  echo $CONNECTION_STRING &&\
  sleep 5 && \
  ./algorand-indexer daemon \
    --server \":${PORT}\" \
    -P \"${CONNECTION_STRING}\" \
    --metrics-mode VERBOSE \
    --algod-net \"${ALGOD_NET}\" \
    --algod-token this-is-secure"]
