# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: IndexerPrometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    httpMethod: POST
    url: prometheus:9090
    version: 1
    editable: false
