{
 "title": "Indexer Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Response Size Byes By URL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(indexer_response_size_bytes_bucket[5m])) by (le,url))"
    }
   ]
  },
  {
   "title": "Request Size Bytes By URL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(indexer_request_size_bytes_bucket[5m])) by (le, url))"
    }
   ]
  },
  {
   "title": "Query Duration By URL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(indexer_request_duration_seconds_bucket[5m])) by (le, url))"
    }
   ]
  }
 ]
}