codecov:
  require_ci_to_pass: no
  branch: develop

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        target: auto
        threshold: 0%
    project: off
