codecov:
  require_ci_to_pass: no
  branch: develop

ignore:
  - "idb/mocks"
  - "idb/dummy"
  - "util/test"
  - "conduit/plugins/processors/filterprocessor/fields/generated_signed_txn_map.go"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        target: auto
        threshold: 0%
    project: off
