before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# Build mac universal binary.
universal_binaries:
  - replace: true

builds:
  - main: ./cmd/algorand-indexer
    binary: algorand-indexer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # skip 386 architecture.
    goarch:
      - amd64
      - arm64
    ldflags: >
      -s -w
      -X github.com/algorand/indexer/v3/version.Hash={{.FullCommit}}
      -X github.com/algorand/indexer/v3/version.ShortHash={{.ShortCommit}}
      -X github.com/algorand/indexer/v3/version.CompileTime={{.Timestamp}}
      -X github.com/algorand/indexer/v3/version.ReleaseVersion={{.Version}}

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "algorand/indexer:latest{{ if .IsSnapshot }}-snapshot{{ end }}-amd64"
    - "algorand/indexer:{{ .Version }}-amd64"
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
    extra_files:
    - docker/docker-entrypoint.sh
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "algorand/indexer:latest{{ if .IsSnapshot }}-snapshot{{ end }}-arm64"
    - "algorand/indexer:{{ .Version }}-arm64"
    build_flag_templates:
    - --platform=linux/arm64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
    extra_files:
    - docker/docker-entrypoint.sh

# automatically select amd64/arm64 when requesting "algorand/indexer"
docker_manifests:
  - name_template: "algorand/indexer:{{ .Version }}"
    image_templates:
    - "algorand/indexer:{{ .Version }}-amd64"
    - "algorand/indexer:{{ .Version }}-arm64"
  - name_template: "algorand/indexer:latest{{ if .IsSnapshot }}-snapshot{{ end }}"
    image_templates:
    - "algorand/indexer:latest{{ if .IsSnapshot }}-snapshot{{ end }}-amd64"
    - "algorand/indexer:latest{{ if .IsSnapshot }}-snapshot{{ end }}-arm64"

# Deb packaging
nfpms:
  - vendor: Algorand
    homepage: https://algorand.com
    maintainer: Algorand <dev@algorand.com>
    description: Indexer API for Algorand blockchain data
    license: MIT
    formats:
      - deb
    file_name_template: "{{ .ConventionalFileName }}"
    contents:
      - src: misc/systemd/
        dst: /lib/systemd/system/
      - src: misc/debian/52algorand-indexer-upgrades
        dst: /etc/apt/apt.conf.d/
        packager: deb

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'

signs:
  - artifacts: checksum

release:
  draft: true
  header: |
    ![GitHub Logo](https://raw.githubusercontent.com/algorand/go-algorand/master/release/release-banner.jpg)
    ## Important

    Indexer {{ .Tag }} uses Conduit for data loading. This is a change from the 2.x version, which managed data loading internally. See our [Using Conduit to Populate an Indexer Database](https://github.com/algorand/conduit/blob/master/docs/tutorials/IndexerWriter.md) tutorial for more information on how to use Conduit.
  footer: |
    **Full Changelog**: https://github.com/algorand/indexer/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---
    [Docker images for this release are available on Docker Hub.](https://hub.docker.com/r/algorand/indexer)
