language: go
go:
  - 1.13.x
  - 1.14.x

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip3 install boto3

script:
  - make
  - go test ./...
  # This script accesses a public bucket. It is disabled because boto3 requires
  # credentials even if the bucket does or not.
  #- python3 misc/e2etest.py
