language: go
go:
- 1.13.x
- 1.14.x
- 1.15.x
dist: bionic
services:
- docker
install:
- go get -u golang.org/x/lint/golint
- pip3 install boto3 markdown2
addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools
    - python3-wheel
script:
- make lint
- make
- make integration
- make test
- ./test/perf.sh "$TEST_CONNECTION_STRING_1" && ./test/perf.sh "$TEST_CONNECTION_STRING_2"
- make fakepackage
- docker build -t e2e_tests -f docker/Dockerfile.mule .
- docker run --rm -t e2e_tests mule/e2e.sh
env:
  global:
  - secure: HdoNiAs9oRMb4Bzv3+A7bKljVLU+y7d+iOihZ+RrIUeMkgu5gkGEvaDX37BrlJh5kszhU+DP/DFVo/SxC6i3mYGNSrilaqoNOK1ZGPrZ+hjYGZ6ifTiAB+XkTJLL4IFkLyj8ys79cJKf2MbdIX53Xe2MrRC1ZiG9geoX5ZR6Nzd1cdb2NZLqSPAtRNDu+0BXXqvIND8enI6sdKi32iIgOATuD5VjJDKSopUke+bd9tNensgDGEx/XujpUPz29ZTQuXAOZDLDYZAJUgiRaBU31bBgGvfe9hck7FyBsnOrepUcH8e1x6DEffrAiWbzy0wH2ZMna0oIrJYc9hHaWTBKVbUQlEIBb+oeWi3jk2GRmrIMrCW9XvhacFU4xSZCQyyU0X63Yt2/69/FiReshoLMKTNO1qlb9Sy0l0Th7qQ3pDvhDGELqE9aWiBk2uvEG2bhBukshZPiW6d30+S0t4ttRXfDD7w9hzo/dGPWwjgd1DjWuaGRAdReVOLgys4JViYfNoaQA0lK4IGyXBdr0B9kSkpD9+YuCqUe5qXA7QtAUI8TyNyGbRMOro7s2r8WgIz/FtUPG/Mw4OGHGiYu6ovWGlh7XBBKqPAneCzQeOupyo1SI8zeeS8apj5PoRhXRzEMsji1f/FkWSMhedsC09wA+QnnUcyooEA4R+k/M3L5N4E=
  - secure: goY/QavSYRU5FuTkVW1dXqTdFEm/jaOVGsip+OVOplODFkMvpFjjedUQ0rkVeXvwuXzxPYYf7ZB2FtKY2ACnxknyZmhKK51c+eqJzwH1GI0bWUW0V6CAfOWyUCY03iTE0kTJaAzhM90fBnQE7Ux/N8Jblaa1QUYPmEAYmK9u7/rJApOc+eiDnXKnvLNg1bJvadxKIoNcJxLuY+5+d73lsUN0ghEhFrwOgIbS5SO7DZudjI+o6dPbgF08VPjqtfDqpTj/0U9iwTi5Vw/hBHW5vN8rNILbvrre03q2rpOPoq5Qemv+q81vNc3hb6cMkBap59+/qEuj/M70AnCM7QxPwBsdMQ5igHY4Mz8c1/x8++DrXrVUkfeNLbJsHK9GADoNzuh1rnGmm+j2ikx+4jLLMGj53FWIDDyi0KeftcL1HBMv6Kl3qnEQ5mpFVBSo+BJ6+APdE/HMxh3/+7PJpeioZ07O+yq+BQBBe3Q7L/kyj4I6J7XUYhFcaeXcr5qRI/ccZ+Sxo6Gp3mi8TR4J2LdTtRQZk1wlU+fhgcKmcDZ3DN8ut1MwOvAwqBeTiMUcdYha4QR+WJRVtKtJjypZnnymCYelQBeboBDrdbjsJlkth8eWf7TlXUy3so542L0f0A/z5q3Z1LLiMj8228x1tbIXxEiteRMZGQiy28g51IvFjLI=
