language: go
go:
- 1.14.x
- 1.15.x
dist: focal
services:
- docker
install:
- go get -u golang.org/x/lint/golint
- pip3 install -r misc/requirements.txt
- if [ -n "$DOCKER_PASSWORD" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; fi
addons:
  apt:
    packages:
    - python3
    - python3-pip
    - python3-setuptools
    - python3-wheel
script:
- test -z `go fmt ./...`
- make lint
- make check
- make integration
- make test
#- ./test/perf.sh "$TEST_CONNECTION_STRING_1" && ./test/perf.sh "$TEST_CONNECTION_STRING_2"
- make fakepackage
# e2elive.py runs with the docker-compose file in misc
- make e2e

after_success:
  - scripts/upload_coverage.sh || true

env:
  global:
  - secure: TM7M7vD5G9Ms7Z60xszC0JEhM9Y9UjCd5bZsLvES0KRD5vOBVALnIc3Y2QzaRmVGatd3sAyg2DYAXPOHbvcMVUX+VLoDwkpMLttgLHONqZbYGB9Z8Cqso9y5NZJe7EYy97uVoWjmLehY4b/v8NY9neNZarT7bwBP8OvdT8JFh3iwNL+w9p7mNm7XPdpY8GHAy5TpGsQfv9p5KZAPiAiTj47EPCZLSdWxlxb4jbeynczTgKu8wo3wRCPAgsmFZv0sVJtzo2c9HE/sz2ypMv++3wF8qCzWt174YBBcHkXCsgUpCL9FlTlwy6B2qW8B1oQxylpot7gce2FE5IpqtBm6ry7n+pFKdgCAKnf69WcHSrFGRVrjfIECxjHzMV4eLEfgHKoMOpfuLWLocQVIc38ii/nrT4I6M2qc79qHfbuC/BW9I+bg5d3cVYg9Wgdt94BhNDcS/b4z+pk7eEsCwPBDau8Nteox20pDTFyHYhK4r4c2dp1kqGGmeqLXzSSfqc81Le+5MUTa4Sn0nI8zfl9x4JCeD+bWL9fC/wwxyU2rYS2chWw1hOAH/nXmUkRTBPYXwyCgW7WPDu2Id2k5ghUh+IRgBxv5v3bOPw1BEPInJqbEwCIIJHICb/jnlg34iWwcSYKmk1TDO4vQVT4AFJq5VzxpvgKnOZSfiCGNMESa3kM=
  - secure: P4HlEYrJ8itstmhK4hDDJojq1zdrv3DzTg7AL9U7FP1qqKq+irIhjRLJGJA3JWyCZfVGIWrf4Ak0LwBwzfBTBA+LZ9HlqfNljrFe3EJzSHd6Ly7RuFYEeslYbDV5BlYv590YivVOB8MzQl5nn6JdqrbKPGKWBvyVLqhL1R87CNvQIA122dVjNz9nqv4G21tOZgx7/PzeUHPSkAImlWg7j3vd2P4IikQr/1vOqnroN1zRXAqMVr3e42wCE0qMeqQ+tFq37Juux2JT9aKZv/wCapwLd1G4FDpbc/wes89dgMp1xGvbpPoltkdP+zbPL0UPdbOGPrW33gVMT4kXkDXZjmHBFyM9xX74gIYcsC+ekzrp9zIRqpXGiCsoW5ZJtjoM4U2fyX427yzceSKDMv7giEEfONnMD1NTYFNpREkrN5zbjMtEi4DgEnNb4e6rVA7CROVXMG8p0WdouM0cvA5j25bE88zW64eqOHtv+hG+RlrROwlM1jKt4CvSlWX5+yaBUdYvl7qCHSP7UlX2JMk0AXGIEfFvO8w4CW3Gyr36DHWedsbU5yawyB/fjX7v9BGAmG1SZThAyf1cwtHN28t4CpoaaCH18spHn+LcrH69ADTFVgsZ5AqULlKCJQCMfa4v5oqaOlmtqSNYTVllXOI+8AqSyHsCYGFPns3RyRfsEhI=
  - secure: PLZW9tmm304LgzJfUMncePdhnKpNZXIrILedk7+41HhPJSps6W9s7/h0Ak6jz8ThGS97nidm44Yoy2O54ft/jmLDSEl7XubNWVjvVvSOJrU1B+cerjzX32ZrzBNI7OIs22JTmP8GKoQqJoMmZy06ltT8OJX2lwuanQidBvUc4GSk33szoS7+BpFtS2x/zvx86fmeYqJOJRKf6AVCWtzYYITEjIR/elbLYHWOBsAxSAdOhVuP2vpN1CqkWYSLlD3SI+5wxjVbPP41rL4m0Vc3Jemv4NDAxjjjuXayy4Tu/3s4O8xBUlMATuXWTKd7dY69+LjGg2vN+Bv3zHIVMyrLxuCGkwjFI40ruBcx7UCv8U3d0ReaZcFSLFzqFszDSftjbHN/gBw8o/JEJ3d/QSqrif2jCxbW+iO74H5fPuB7O+N34gZBopllH6tZlGqCI2lRgsXpAqNC50/Jtaab8bkRFB2Eoz7EolXscYkvJgi/C6blvsMZVMfLi0WPgi6/8HznB4o/lh3Y4eND2BBiaaXOIn0zi1EmeMpqlFdr3oH2HIAgYXNDOkHsiQfDfRZowOadpCDhQVpf17vAJ7kpgEjt47jYCNoYimLklh2T88sdtqAYAF8ACyyOf7Be87xtq6jmFaxpT6f+DYO3K3p3P9HJfRO8pwuP61yPSOvAmLwU38A=
