language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

dist: bionic

services:
  - docker

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel

install:
  - pip3 install boto3 markdown2

script:
  - make
  - make migration-tests
  - make test
  - make fakepackage
  - docker build -t e2e_tests -f docker/Dockerfile.mule .
  - docker run --rm -t e2e_tests mule/e2e.sh
