FROM ubuntu:18.04

ARG GO_VERSION=1.13.11
ENV DEBIAN_FRONTEND noninteractive
ENV GOROOT /usr/local/go
ENV GOPATH /app/go
ENV PATH /usr/local/go/bin:$PATH
ENV USER root
RUN apt-get update && apt-get -y install wget build-essential python3 python3-pip
RUN pip3 install markdown2
RUN cd /tmp && wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz \
  && tar -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
  mv -i go /usr/local && mkdir -p /app/go/src/github.com/algorand/indexer
COPY ./ /app/go/src/github.com/algorand/indexer/
WORKDIR /app/go/src/github.com/algorand/indexer/
CMD python3 misc/release.py
