agents:
  - name: ubuntu
    dockerFilePath: docker/Dockerfile.mule
    image: algorand/indexer-ci-linux
    version: README.md
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
    workDir: $HOME/projects/indexer

tasks:
  - task: docker.Make
    name: package
    agent: ubuntu
    target: package

  - task: s3.BucketCopy
    name: stage
    src: $HOME/projects/indexer/tmp/node_pkgs/linux/amd64/$VERSION
    dest: s3://$STAGING/indexer/$VERSION

  - task: docker.Make
    name: sign
    agent: ubuntu
    target: sign

  - task: docker.Make
    name: deploy
    agent: ubuntu
    target: deploy

  - task: docker.Make
    name: test
    agent: ubuntu
    target: test

  - task: docker.Make
    name: test-package
    agent: ubuntu
    target: test-package

jobs:
  deploy:
    tasks:
      - docker.Make.deploy

  package:
    tasks:
      - docker.Make.package

  sign:
    tasks:
      - docker.Make.sign

  stage:
    tasks:
      - s3.BucketCopy.stage

  test:
    tasks:
      - docker.Make.test

  test-package:
    tasks:
      - docker.Make.test-package

