tasks:
  - task: shell.docker.Ensure
    name: ubuntu
    image: algorand/indexer-ci-linux
    version: latest
    dockerFilePath: Dockerfile

  - task: docker.Make
    name: package
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
    target: package

  - task: s3.BucketCopy
    name: stage
    src: $HOME/projects/indexer/tmp/node_pkgs/linux/amd64/$VERSION
    dest: s3://algorand-staging/indexer/$VERSION

  - task: s3.BucketCopy
    name: stage-releases-page
    src: $HOME/projects/indexer/tmp/node_pkgs/linux/amd64/$VERSION/releases.html
    dest: s3://algorand-staging/indexer/$VERSION

  - task: docker.Make
    name: sign
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: sign

  - task: docker.Make
    name: deploy
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: deploy

  - task: docker.Make
    name: test
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      volumes: [
        /var/run/docker.sock:/var/run/docker.sock
      ]
    target: test

  - task: docker.Make
    name: test-package
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      volumes: [
        /var/run/docker.sock:/var/run/docker.sock
      ]
    target: test-package

jobs:
  deploy:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.deploy

  package:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.package

  sign:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.sign

  stage:
    tasks:
      - s3.BucketCopy.stage

  stage-releases-page:
    tasks:
      - s3.BucketCopy.stage-releases-page

  test:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.test

  test-package:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.test-package

