tasks:
  - task: shell.docker.Ensure
    name: ubuntu
    image: algorand/indexer-ci-linux
    version: latest
    dockerFilePath: docker/Dockerfile.mule

  - task: docker.Make
    name: package
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
    target: package

  - task: s3.BucketCopy
    name: stage
    src: $HOME/projects/indexer/tmp/node_pkgs/linux/amd64
    dest: s3://algorand-staging/indexer/$FULLVERSION

  - task: docker.Make
    name: sign-deb
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: mule-sign-deb WORKDIR=/projects/indexer

  - task: docker.Make
    name: sign-tarball
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: mule-sign-tar.bz2 WORKDIR=/projects/indexer

  - task: docker.Make
    name: deploy-deb
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      env: [
        AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      ]
      volumes: [
        $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent,
        $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
      ]
    target: mule-deploy-deb WORKDIR=/projects/indexer

  - task: docker.Make
    name: test
    docker:
      image: algorand/indexer-ci-linux
      version: latest
      workDir: /projects/indexer
      volumes: [
        /var/run/docker.sock:/var/run/docker.sock
      ]
    target: mule-test WORKDIR=/projects/indexer

  - task: s3.BucketCopy
    name: setup-deb
    src: s3://algorand-staging/indexer/$FULLVERSION/*.deb
    dest: /projects/indexer/packages/$FULLVERSION

  - task: s3.BucketCopy
    name: setup-tarball
    src: s3://algorand-staging/indexer/$FULLVERSION/*.tar.bz2
    dest: /projects/indexer/packages/$FULLVERSION

jobs:
  package:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.package

  stage:
    tasks:
      - s3.BucketCopy.stage

  sign:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.sign-deb
      - docker.Make.sign-tarball

  test:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.test

  deploy:
    configs:
      arch: amd64
    tasks:
      - shell.docker.Ensure.ubuntu
      - docker.Make.deploy-deb

  package-setup-deb:
    tasks:
      - s3.BucketCopy.setup-deb

  package-setup-tarball:
    tasks:
      - s3.BucketCopy.setup-tarball

