{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(indexer_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "request duration (sec)"
    }
   ]
  },
  {
   "title": "Request Duration by URL",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(indexer_request_duration_seconds_bucket[5m])) by (le, url))"
    }
   ]
  },
  {
   "title": "Postgres Eval Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(indexer_daemon_postgres_eval_time_sec_sum[1m])",
     "legendFormat": "eval_time(sec)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "Heap Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(go_memstats_heap_alloc_bytes[$__interval])",
     "legendFormat": "alloc_bytes"
    }
   ]
  },
  {
   "title": "postgres db",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT relname, seq_tup_read,idx_scan,idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup,\nn_dead_tup,last_vacuum,last_autovacuum\n\nFROM pg_stat_user_tables"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT query, calls,rows,mean_exec_time, \nmin_exec_time,max_exec_time\nFROM pg_stat_statements\nORDER BY mean_exec_time DESC"
    }
   ]
  },
  { "title": "Importing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(indexer_daemon_imported_tx_per_block_sum{}[$__interval])/rate(indexer_daemon_imported_round[$__interval])",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Block import",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(indexer_daemon_get_algod_raw_block_time_sec_sum{}[$__interval])",
     "legendFormat": "Get Algod Raw Block Response time(sec)"
    },
    {
     "expr": "rate(indexer_daemon_imported_tx_per_block_sum{}[$__interval])",
     "legendFormat": "txns per block"
    },
    {
     "expr": "rate(indexer_daemon_import_time_sec_sum[$__interval])",
     "legendFormat": "block import time (sec)"
    }
   ]
  },
  {
   "title": "Round",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "indexer_daemon_imported_round{}",
     "legendFormat": "total rounds"
    },
    {
     "expr": "rate(indexer_daemon_imported_round[$__interval])",
     "legendFormat": "rounds imported"
    }
   ]
  },
  {
   "title": "Txns per block by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "expr": "indexer_daemon_imported_txns", "legendFormat": "{{txn_type}}" }
   ]
  }
 ]
}