ARG GO_VERSION=1.17.5
FROM golang:$GO_VERSION

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y apt-utils curl git git-core bsdmainutils python3


# Build go-algorand
RUN mkdir /work
WORKDIR /work
ADD . ./
WORKDIR /work/third_party/go-algorand
RUN ./scripts/configure_dev.sh
RUN make

# Build indexer
WORKDIR /work
RUN make
WORKDIR /work/cmd/algorand-indexer
ENV CGO_ENABLED="1"
RUN go build

# The sleep is to wait until postgres starts
CMD ["/bin/sh", "-c", "\
  echo $ALGOD_NET && \
  echo $CONNECTION_STRING &&\
  sleep 5 && \
  ./algorand-indexer daemon \
    --server \":${PORT}\" \
    -P \"${CONNECTION_STRING}\" \
    --metrics-mode VERBOSE \
    --algod-net \"${ALGOD_NET}\" \
    --algod-token ${ALGOD_TOKEN}"]