services:
  indexer:
    container_name: "indexer"
    build:
      context: ./../
      dockerfile: "./monitoring/Dockerfile-indexer"
    environment:
      PORT: 8888
      CONNECTION_STRING: ${DB_CONNECTION:-"host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"}
      ALGOD_NET: ${ALGOD_NET}
      ALGOD_TOKEN: ${ALGOD_TOKEN}
    ports:
      - 8888:8888
    depends_on:
      - indexer-db

  indexer-db:
    image: "postgres:13-alpine"
    container_name: "indexer-postgres"
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"

  prometheus:
    image: "prom/prometheus"
    container_name: "prometheus"
    ports:
      - 9090:9090
    volumes:
      # Install prometheus config
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: "grafana/grafana:8.4.2"
    container_name: "grafana"
    ports:
      - 3000:3000
    environment:
      GF_PATHS_CONFIG: /etc/grafana/ours.ini
    volumes:
      - ./grafana.ini:/etc/grafana/ours.ini
      - ./grafana_prometheus_datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      # Modify the dashboard with the web interface. Once finished export the
      # JSON from the share menu (from the dashboard page), convert the JSON to
      # YAML, and update this YAML file.
      #
      # This didn't work, maybe because the metrics don't exist when initialized?
      # The dashboard can be imported manually.
      #- ./grafana_indexer_dashboard.yml:/etc/grafana/provisioning/dashboards/indexer.yml


