name: "Asset Destroy"
genesis_acocunts: 1000000
genesis_account_balance: 100000000
tx_per_block: 5000

# transaction distribution
tx_distribution_asset: 1.0

# asset config
asset_create_rate: 0.8
asset_destroy_rate: 0.2
asset_optin_rate: 0.0
asset_close_rate: 0.0
