name: "Asset Destroy"
genesis_acocunts: 1000000
genesis_account_balance: 100000000
tx_per_block: 5000

# transaction distribution
tx_asset_fraction: 1.0

# asset config
asset_create_fraction: 0.8
asset_destroy_fraction: 0.2
asset_optin_fraction: 0.0
asset_close_fraction: 0.0
