name: "Asset Xfer"
genesis_acocunts: 1000000
genesis_account_balance: 100000000
tx_per_block: 5000

# transaction distribution
tx_distribution_asset: 1.0

# asset config
asset_create_rate: 0.001
asset_optin_rate: 0.10
asset_xfer_rate: 0.899
