name: "Asset Xfer"
genesis_acocunts: 1000000
genesis_account_balance: 100000000
tx_per_block: 5000

# transaction distribution
tx_asset_fraction: 1.0

# asset config
asset_create_fraction: 0.001
asset_optin_fraction: 0.10
asset_xfer_fraction: 0.899
